language: android
jdk: oraclejdk8

env:
 global:
 - ANDROID_API=27
 - ANDROID_BUILD_TOOLS=28.0.0

android:
 components:
  - tools
  - tools # Running this twice get's the latest build tools
  - platform-tools
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra

install:
  - echo yes | sdkmanager "build-tools;28.0.0"