sudo: false

language: android
jdk: oraclejdk8

env:
 global:
 - ANDROID_API=27
 - ANDROID_BUILD_TOOLS=28.0.0
 - ANDROID_ABI=armeabi-v7a

android:
 components:
  - tools
  - tools # Running this twice get's the latest build tools
  - platform-tools
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra
  - sys-img-armeabi-v7a-android-$ANDROID_API
  - sys-img-armeabi-v7a-android-17

install:
  - echo yes | sdkmanager "build-tools;28.0.0-rc1"

before_script:
  - echo no | android create avd --force -n test -t android-${ANDROID_API} --abi ${ANDROID_ABI}
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &