language: android
jdk: oraclejdk8

env:
 global:
 - ANDROID_API=21
 - ANDROID_BUILD_TOOLS=28.0.0
 - ANDROID_ABI=armeabi-v7a
 - ANDROID_TAG=google_apis
 - ADB_INSTALL_TIMEOUT=8

android:
 components:
  - tools
  - tools # Running this twice get's the latest build tools
  - platform-tools
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra
  - sys-img-armeabi-v7a-google_apis-21
  - sys-img-armeabi-v7a-google_apis-21

install:
  - echo yes | sdkmanager "build-tools;28.0.0-rc1"

before_script:
  - echo no | android create avd --force -n test -t "android-21" --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-window &
  - travis_wait android-wait-for-emulator
  - travis_wait adb shell input keyevent 82 &
  
script:
  - ./gradlew clean
  - ./gradlew assembleDebug
  - ./gradlew assembleDebugAndroidTest
  - adb install app/build/outputs/apk/debug/app-debug.apk
  - ./gradlew connectedAndroidTest coveralls