sudo: false

language: android
jdk: oraclejdk8

env:
 global:
 - ANDROID_API=23
 - ANDROID_BUILD_TOOLS=28.0.0
 - ANDROID_ABI=armeabi-v7a
 - ANDROID_TAG=google_apis

android:
 components:
  - tools
  - tools # Running this twice get's the latest build tools
  - platform-tools
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra
  - sys-img-armeabi-v7a-google_apis-23
  - sys-img-armeabi-v7a-google_apis-23

install:
  - echo yes | sdkmanager "build-tools;28.0.0-rc1"

before_script:
  - echo no | android create avd --force -n test -t "android-23" --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./wait_for_emulator
